In [1]:
# boilerplate imports
import numpy as np
import scipy as scipy

In [24]:
# simple for loop
size=10
v=np.array([])
for i in np.arange(size):
    v = np.append(v,2**(i+1))
print(v)
    

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


In [25]:
# while loop
size=5
i=0
while i<=size-1:
    v[i]=100
    i=i+1
print(v)
    

[ 100.  100.  100.  100.  100.   64.  128.  256.  512. 1024.]


In [27]:
# while with break
size=4
i=0
while i<999:
    v[i]=999
    i=i+1
    if i==size:
        break
print(v)


[ 999.  999.  999.  999.  100.   64.  128.  256.  512. 1024.]


In [31]:
# if/else
v[0]=3
if v[0]==1:
    print("The value is one")
elif v[0]==2:
    print("The value is two")
else:
    print("The value is not one or two")
    

The value is not one or two


In [34]:
# define a function 
def squarethisnumber(x):
    return x**2
y=squarethisnumber(5)
print(y)

25


In [42]:
# define a function with two values as results
def squareandcubethisnumber(x):
    return [x**2, x**3]
y=squareandcubethisnumber(5)
print(y)

[25, 125]


In [58]:
# define a function to find the cost function
x = np.array([[1,1],[1,2],[1,3]])
print(x)
y = np.array([[1],[2],[3]])
print(y)
theta = np.array([[0],[0]])
 
def costFunctionJ(x,y,theta):
    ''' X is the "design matrix" containing our training examples
        Y is the class labels'''
    m = len(x)              # number of training examples
    predictions = x@theta   # predictions of hypothesis on all m examples;  remember @ is matrix multiply
    sqrErrors = (predictions-y)**2   # squared errors
    return 1/(2*m)*sum(sqrErrors)
    
j = costFunctionJ(x,y,theta)
print("j =",j[0])

[[1 1]
 [1 2]
 [1 3]]
[[1]
 [2]
 [3]]
j = 2.333333333333333
