## Python practice for Coursera machine learning MOOC

In [114]:
import numpy as np
import math

Basic array creation and indexing.  First element is 0.

In [4]:
x=np.array([[1, 2, 3], [4, 5, 6]])

In [6]:
x.shape

(2, 3)

In [7]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
x[:,1]

array([2, 5])

In [12]:
y=x[0,0]+5
y

6

Load a CSV

In [21]:
filename='testdata1.txt'
raw_testdata1=open(filename)
testdata1=np.loadtxt(raw_testdata1, delimiter=",")

In [24]:
testdata1[1,1]

12.0

### Recreate the Octave examples Ang goes through in Octave tutoral 'computing on data'

In [66]:
A=np.array([[1,2],[3,4],[5,6]])
B=np.array([[11,12],[13,14],[15,16]])
C=np.array([[1,1],[2,2]])

Default is element-wise arithmatic

In [29]:
A*B

array([[11, 24],
       [39, 56],
       [75, 96]])

In [30]:
A+B

array([[12, 14],
       [16, 18],
       [20, 22]])

In [31]:
2*C

array([[2, 2],
       [4, 4]])

In [34]:
1/A

array([[1.        , 0.5       ],
       [0.33333333, 0.25      ],
       [0.2       , 0.16666667]])

In [44]:
2**A

array([[ 2,  4],
       [ 8, 16],
       [32, 64]], dtype=int32)

In [33]:
A@np.transpose(B)

array([[ 35,  41,  47],
       [ 81,  95, 109],
       [127, 149, 171]])

In [118]:
A_inv=np.linalg.pinv(A)

In [43]:
C@C

array([[3, 3],
       [6, 6]])

In [119]:
A_inv@A

array([[ 1.00000000e+00, -8.88178420e-16],
       [ 1.77635684e-15,  1.00000000e+00]])

numpy operations work elementwise on arrays, math operations only accept scalars

In [48]:
np.exp(C)

array([[2.71828183, 2.71828183],
       [7.3890561 , 7.3890561 ]])

In [45]:
np.log(C)

array([[0.        , 0.        ],
       [0.69314718, 0.69314718]])

In [46]:
math.log(C)

TypeError: only size-1 arrays can be converted to Python scalars

In [50]:
abs(C)

array([[1, 1],
       [2, 2]])

In [52]:
C+np.ones(np.shape(C))

array([[2., 2.],
       [3., 3.]])

In [53]:
C+1

array([[2, 2],
       [3, 3]])

In [54]:
np.transpose(A)

array([[1, 3, 5],
       [2, 4, 6]])

Array max returns only the value not the index

In [67]:
np.amax(A)

6

By default the index of the max is given for a flattened array.

In [71]:
np.argmax(A)

5

unravel_index converts it back to an index for the given shape - arrayname.shape is the correct shape

In [72]:
ind=np.unravel_index(np.argmax(A),A.shape)
ind

(2, 1)

In [73]:
A[ind]

6

Logical operations

In [74]:
C<2

array([[ True,  True],
       [False, False]])

logicals can be used like indicies to find the elements in the array.  Here find the elements of C that are > 3

In [79]:
test=np.greater(C,1)
test

array([[False, False],
       [ True,  True]])

In [80]:
C[test]

array([2, 2])

Sum along specified axis.  Note 0 indexing is a thing

In [92]:
M=np.random.random((8,8))
M

array([[0.01621026, 0.55601291, 0.30798011, 0.56978265, 0.9631996 ,
        0.66258725, 0.96857739, 0.79399889],
       [0.22093878, 0.54420004, 0.63193705, 0.16639656, 0.43544555,
        0.96102318, 0.13455764, 0.19619074],
       [0.87341885, 0.75427477, 0.04510899, 0.54996966, 0.88704674,
        0.45721556, 0.36056285, 0.90954337],
       [0.43486471, 0.08121791, 0.06023801, 0.00329008, 0.05044891,
        0.35879892, 0.98264729, 0.34452278],
       [0.11553677, 0.62289812, 0.72581068, 0.17240081, 0.70980266,
        0.05030995, 0.86220117, 0.63060544],
       [0.83868374, 0.11733304, 0.48904678, 0.53383305, 0.90493877,
        0.62869178, 0.23742698, 0.75995068],
       [0.79059527, 0.13463581, 0.96038955, 0.26031429, 0.44609343,
        0.44059668, 0.90652508, 0.60805503],
       [0.99735752, 0.91694262, 0.44558204, 0.4172159 , 0.25721274,
        0.21973034, 0.27119638, 0.3876312 ]])

In [93]:
np.sum(M,0)

array([4.28760591, 3.72751522, 3.66609321, 2.673203  , 4.6541884 ,
       3.77895365, 4.72369477, 4.63049813])

In [95]:
np.sum(M,1)

array([4.83834906, 3.29068954, 4.83714079, 2.3160286 , 3.88956559,
       4.50990483, 4.54720514, 3.91286875])

Eliminate all but diagonal elements of M by elementwise multiplication with identity

In [108]:
M_diag=M*np.eye(M.shape[1])
M_diag

array([[0.01621026, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.54420004, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.04510899, 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.00329008, 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.70980266,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.62869178, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.90652508, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.3876312 ]])

Sum along rows

In [107]:
np.sum(M_diag,0)

array([0.01621026, 0.54420004, 0.04510899, 0.00329008, 0.70980266,
       0.62869178, 0.90652508, 0.3876312 ])

Sum along rows then sum them all.  Here this is the sum of the diagonal elements of the original M array

In [110]:
np.sum(np.sum(M_diag,0),0)

3.2414600946831555